// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HHPW.Migrations
{
    [DbContext(typeof(HHPWDbContext))]
    [Migration("20240413170238_SecondCreate")]
    partial class SecondCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HHPW.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("price")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Widget",
                            price = 10
                        },
                        new
                        {
                            Id = 2,
                            Name = "Gadget",
                            price = 20
                        },
                        new
                        {
                            Id = 3,
                            Name = "Thingamajig",
                            price = 15
                        },
                        new
                        {
                            Id = 4,
                            Name = "Doohickey",
                            price = 25
                        });
                });

            modelBuilder.Entity("HHPW.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Phone")
                        .HasColumnType("bigint");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<int>("Tip")
                        .HasColumnType("integer");

                    b.Property<int>("Total")
                        .HasColumnType("integer");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 4, 11, 12, 2, 38, 291, DateTimeKind.Local).AddTicks(2002),
                            Email = "john@example.com",
                            Name = "John Doe",
                            OrderType = "Online",
                            PaymentType = "Credit Card",
                            Phone = 1234567890L,
                            Status = true,
                            Tip = 5,
                            Total = 50,
                            userId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 4, 12, 12, 2, 38, 291, DateTimeKind.Local).AddTicks(2131),
                            Email = "jane@example.com",
                            Name = "Jane Smith",
                            OrderType = "In-store",
                            PaymentType = "PayPal",
                            Phone = 9876543210L,
                            Status = false,
                            Tip = 3,
                            Total = 30,
                            userId = 2
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2024, 4, 13, 12, 2, 38, 291, DateTimeKind.Local).AddTicks(2135),
                            Email = "alice@example.com",
                            Name = "Alice Johnson",
                            OrderType = "Delivery",
                            PaymentType = "Cash",
                            Phone = 5551234567L,
                            Status = true,
                            Tip = 4,
                            Total = 45,
                            userId = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
